version: "3.9"
services:
  hummingbot:
    container_name: hummingbot
    image: hummingbot/hummingbot:latest
    volumes:
      - "./hummingbot_files/conf:/home/hummingbot/conf"
      - "./hummingbot_files/conf/scripts:/home/hummingbot/conf/scripts"
      - "./hummingbot_files/logs:/home/hummingbot/logs"
      - "./hummingbot_files/data:/home/hummingbot/data"
      - "./hummingbot_files/scripts:/home/hummingbot/scripts"
    environment:
      - CONFIG_PASSWORD=a
      - CONFIG_FILE_NAME=download_ob_and_trades.py
      - EXCHANGE=mexc_paper_trade
      - TRADING_PAIRS=SKO-USDT
      - DEPTH=50
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host